GET http://localhost:8080/index

###
POST http://localhost:8080/register
Content-Type: application/json

{
   "e":"6306021610080@fitm.kmutnb.ac.th",
    "password": "123",
    "name":"พัชรพร มุ่งทวีเกียรติ"
}


    
    
     
